# encoding: utf-8
# module samba.dcerpc.dcerpc
# from /usr/lib/python2.7/dist-packages/samba/dcerpc/dcerpc.so
# by generator 1.143
""" dcerpc DCE/RPC """

# imports
import talloc as __talloc


# Variables with simple values

DCERPC_AUTH_LEN_OFFSET = 10

DCERPC_AUTH_LEVEL_CALL = 3
DCERPC_AUTH_LEVEL_CONNECT = 2
DCERPC_AUTH_LEVEL_DEFAULT = 2
DCERPC_AUTH_LEVEL_INTEGRITY = 5
DCERPC_AUTH_LEVEL_NONE = 1
DCERPC_AUTH_LEVEL_PACKET = 4
DCERPC_AUTH_LEVEL_PRIVACY = 6

DCERPC_AUTH_PAD_ALIGNMENT = 16

DCERPC_AUTH_TRAILER_LENGTH = 8

DCERPC_AUTH_TYPE_DIGEST = 21
DCERPC_AUTH_TYPE_DPA = 17
DCERPC_AUTH_TYPE_KRB5 = 16

DCERPC_AUTH_TYPE_KRB5_1 = 1

DCERPC_AUTH_TYPE_MSMQ = 100
DCERPC_AUTH_TYPE_MSN = 18

DCERPC_AUTH_TYPE_NCALRPC_AS_SYSTEM = 200

DCERPC_AUTH_TYPE_NONE = 0
DCERPC_AUTH_TYPE_NTLMSSP = 10
DCERPC_AUTH_TYPE_SCHANNEL = 68
DCERPC_AUTH_TYPE_SPNEGO = 9

DCERPC_BIND_ACK_REASON_ABSTRACT_SYNTAX_NOT_SUPPORTED = 1

DCERPC_BIND_ACK_REASON_LOCAL_LIMIT_EXCEEDED = 3

DCERPC_BIND_ACK_REASON_NOT_SPECIFIED = 0

DCERPC_BIND_ACK_REASON_TRANSFER_SYNTAXES_NOT_SUPPORTED = 2

DCERPC_BIND_ACK_RESULT_ACCEPTANCE = 0

DCERPC_BIND_ACK_RESULT_NEGOTIATE_ACK = 3

DCERPC_BIND_ACK_RESULT_PROVIDER_REJECTION = 2

DCERPC_BIND_ACK_RESULT_USER_REJECTION = 1

DCERPC_BIND_NAK_REASON_INVALID_AUTH_TYPE = 8

DCERPC_BIND_NAK_REASON_INVALID_CHECKSUM = 9

DCERPC_BIND_NAK_REASON_LOCAL_LIMIT_EXCEEDED = 2

DCERPC_BIND_NAK_REASON_NOT_SPECIFIED = 0

DCERPC_BIND_NAK_REASON_PROTOCOL_VERSION_NOT_SUPPORTED = 4

DCERPC_BIND_NAK_REASON_TEMPORARY_CONGESTION = 1

DCERPC_BIND_PROVIDER_REJECT = 2

DCERPC_BIND_REASON_ASYNTAX = 1

DCERPC_BIND_REASON_INVALID_AUTH_TYPE = 8

DCERPC_BIND_TIME_KEEP_CONNECTION_ON_ORPHAN = 2

DCERPC_BIND_TIME_SECURITY_CONTEXT_MULTIPLEXING = 1

DCERPC_DREP_LE = 16
DCERPC_DREP_OFFSET = 4

DCERPC_FAULT_ACCESS_DENIED = 5

DCERPC_FAULT_BAD_STUB_DATA = 1783

DCERPC_FAULT_CANT_PERFORM = 1752

DCERPC_FAULT_CONTEXT_MISMATCH = 469762074

DCERPC_FAULT_INVALID_TAG = 469762054

DCERPC_FAULT_NDR = 1783

DCERPC_FAULT_NO_CALL_ACTIVE = 1725

DCERPC_FAULT_OP_RNG_ERROR = 469827586

DCERPC_FAULT_OTHER = 1

DCERPC_FAULT_OUT_OF_RESOURCES = 1753

DCERPC_FAULT_SEC_PKG_ERROR = 1825

DCERPC_FAULT_TODO = 66

DCERPC_FAULT_UNK_IF = 469827587

DCERPC_FRAG_LEN_OFFSET = 8

DCERPC_FRAG_MAX_SIZE = 5840

DCERPC_NCACN_PAYLOAD_MAX_SIZE = 4194304

DCERPC_NCACN_PAYLOAD_OFFSET = 16

DCERPC_NCA_S_COMM_FAILURE = 469827585

DCERPC_NCA_S_FAULT_ADDR_ERROR = 469762050

DCERPC_NCA_S_FAULT_BAD_ACTID = 469762058

DCERPC_NCA_S_FAULT_CANCEL = 469762061

DCERPC_NCA_S_FAULT_CODESET_CONV_ERROR = 469762083

DCERPC_NCA_S_FAULT_CONTEXT_MISMATCH = 469762074

DCERPC_NCA_S_FAULT_FP_DIV_BY_ZERO = 469762051

DCERPC_NCA_S_FAULT_FP_ERROR = 469762063
DCERPC_NCA_S_FAULT_FP_OVERRFLOW = 469762053
DCERPC_NCA_S_FAULT_FP_UNDERFLOW = 469762052

DCERPC_NCA_S_FAULT_ILL_INST = 469762062

DCERPC_NCA_S_FAULT_INT_DIV_BY_ZERO = 469762049

DCERPC_NCA_S_FAULT_INT_OVERFLOW = 469762064

DCERPC_NCA_S_FAULT_INVALID_BOUND = 469762055
DCERPC_NCA_S_FAULT_INVALID_TAG = 469762054

DCERPC_NCA_S_FAULT_MANAGER_NOT_ENTERED = 469762060

DCERPC_NCA_S_FAULT_NO_CLIENT_STUB = 469762085

DCERPC_NCA_S_FAULT_OBJECT_NOT_FOUND = 469762084

DCERPC_NCA_S_FAULT_PIPE_CLOSED = 469762069

DCERPC_NCA_S_FAULT_PIPE_COMM_ERROR = 469762072

DCERPC_NCA_S_FAULT_PIPE_DISCIPLINE = 469762071
DCERPC_NCA_S_FAULT_PIPE_EMPTY = 469762068
DCERPC_NCA_S_FAULT_PIPE_MEMORY = 469762073
DCERPC_NCA_S_FAULT_PIPE_ORDER = 469762070

DCERPC_NCA_S_FAULT_REMOTE_COMM_FAILURE = 469762067

DCERPC_NCA_S_FAULT_REMOTE_NO_MEMORY = 469762075

DCERPC_NCA_S_FAULT_RPC_VERSION_MISMATCH = 469762056

DCERPC_NCA_S_FAULT_STRING_TOO_LARGE = 469827605

DCERPC_NCA_S_FAULT_TX_OPEN_FAILED = 469762082

DCERPC_NCA_S_FAULT_UNSPEC = 469762066

DCERPC_NCA_S_FAULT_UNSPEC_REJECT = 469762057

DCERPC_NCA_S_FAULT_USER_DEFINED = 469762081

DCERPC_NCA_S_FAULT_WHO_ARE_YOU_FAILED = 469762059

DCERPC_NCA_S_INVALID_CHECKSUM = 469762079
DCERPC_NCA_S_INVALID_CRC = 469762080

DCERPC_NCA_S_INVALID_PRES_CONTEXT_ID = 469762076

DCERPC_NCA_S_OP_RNG_ERROR = 469827586

DCERPC_NCA_S_OUT_ARGS_TOO_BIG = 469827603

DCERPC_NCA_S_PROTO_ERROR = 469827595

DCERPC_NCA_S_SERVER_TOO_BUSY = 469827604

DCERPC_NCA_S_UNKNOWN_IF = 469827587

DCERPC_NCA_S_UNSUPPORTED_AUTHN_LEVEL = 469762077

DCERPC_NCA_S_UNSUPPORTED_TYPE = 469827607

DCERPC_NCA_S_UNUSED_1C000011 = 469762065
DCERPC_NCA_S_UNUSED_1C00001E = 469762078

DCERPC_NCA_S_WRONG_BOOT_TIME = 469827590

DCERPC_NCA_S_YOU_CRASHED = 469827593

DCERPC_PFC_FLAG_CONC_MPX = 16

DCERPC_PFC_FLAG_DID_NOT_EXECUTE = 32

DCERPC_PFC_FLAG_FIRST = 1
DCERPC_PFC_FLAG_LAST = 2
DCERPC_PFC_FLAG_MAYBE = 64

DCERPC_PFC_FLAG_OBJECT_UUID = 128

DCERPC_PFC_FLAG_PENDING_CANCEL = 4

DCERPC_PFC_FLAG_PENDING_CANCEL_OR_HDR_SIGNING = 4

DCERPC_PFC_FLAG_SUPPORT_HEADER_SIGN = 4

DCERPC_PFC_OFFSET = 3

DCERPC_PKT_ACK = 7
DCERPC_PKT_ALTER = 14

DCERPC_PKT_ALTER_RESP = 15

DCERPC_PKT_AUTH3 = 16
DCERPC_PKT_BIND = 11

DCERPC_PKT_BIND_ACK = 12
DCERPC_PKT_BIND_NAK = 13

DCERPC_PKT_CANCEL_ACK = 10

DCERPC_PKT_CL_CANCEL = 8

DCERPC_PKT_CO_CANCEL = 18

DCERPC_PKT_FACK = 9
DCERPC_PKT_FAULT = 3
DCERPC_PKT_NOCALL = 5
DCERPC_PKT_ORPHANED = 19
DCERPC_PKT_PING = 1
DCERPC_PKT_REJECT = 6
DCERPC_PKT_REQUEST = 0
DCERPC_PKT_RESPONSE = 2
DCERPC_PKT_RTS = 20
DCERPC_PKT_SHUTDOWN = 17
DCERPC_PKT_WORKING = 4

DCERPC_REQUEST_LENGTH = 24

DCERPC_RESPONSE_LENGTH = 24

DCERPC_SEC_VT_CLIENT_SUPPORTS_HEADER_SIGNING = 1

DCERPC_SEC_VT_COMMAND_BITMASK1 = 1
DCERPC_SEC_VT_COMMAND_END = 16384
DCERPC_SEC_VT_COMMAND_ENUM = 16383
DCERPC_SEC_VT_COMMAND_HEADER2 = 3
DCERPC_SEC_VT_COMMAND_PCONTEXT = 2

DCERPC_SEC_VT_MAX_SIZE = 1024

DCERPC_SEC_VT_MUST_PROCESS = 32768

DECRPC_BIND_PROTOCOL_VERSION_NOT_SUPPORTED = 4

FDClient = 0
FDInProxy = 1
FDOutProxy = 3
FDServer = 2

RTS_FLAG_ECHO = 64
RTS_FLAG_EOF = 32

RTS_FLAG_IN_CHANNEL = 8

RTS_FLAG_NONE = 0

RTS_FLAG_OTHER_CMD = 2

RTS_FLAG_OUT_CHANNEL = 16

RTS_FLAG_PING = 1

RTS_FLAG_RECYCLE_CHANNEL = 4

RTS_IPV4 = 0
RTS_IPV6 = 1

# no functions
# classes

from ack import ack
from ack_ctx import ack_ctx
from auth import auth
from auth3 import auth3
from bind import bind
from bind_ack import bind_ack
from bind_nak import bind_nak
from bind_nak_version import bind_nak_version
from cancel_ack import cancel_ack
from ClientAddress import ClientAddress
from cl_cancel import cl_cancel
from co_cancel import co_cancel
from ctx_list import ctx_list
from empty import empty
from fack import fack
from fault import fault
from FlowControlAcknowledgment import FlowControlAcknowledgment
from ncacn_packet import ncacn_packet
from ncadg_packet import ncadg_packet
from orphaned import orphaned
from ping import ping
from request import request
from response import response
from rts import rts
from RTSCookie import RTSCookie
from rts_cmd import rts_cmd
from rts_cmd_ANCE import rts_cmd_ANCE
from rts_cmd_AssociationGroupId import rts_cmd_AssociationGroupId
from rts_cmd_ChannelLifetime import rts_cmd_ChannelLifetime
from rts_cmd_ClientAddress import rts_cmd_ClientAddress
from rts_cmd_ClientKeepalive import rts_cmd_ClientKeepalive
from rts_cmd_ConnectionTimeout import rts_cmd_ConnectionTimeout
from rts_cmd_Cookie import rts_cmd_Cookie
from rts_cmd_Destination import rts_cmd_Destination
from rts_cmd_Empty import rts_cmd_Empty
from rts_cmd_FlowControlAck import rts_cmd_FlowControlAck
from rts_cmd_NegativeANCE import rts_cmd_NegativeANCE
from rts_cmd_Padding import rts_cmd_Padding
from rts_cmd_PingTrafficSentNotify import rts_cmd_PingTrafficSentNotify
from rts_cmd_ReceiveWindowSize import rts_cmd_ReceiveWindowSize
from rts_cmd_Version import rts_cmd_Version
from sec_verification_trailer import sec_verification_trailer
from sec_vt import sec_vt
from sec_vt_count import sec_vt_count
from sec_vt_header2 import sec_vt_header2
from sec_vt_pcontext import sec_vt_pcontext
from shutdown import shutdown
from working import working
