# encoding: utf-8
# module samba.dcerpc.dnsserver
# from /usr/lib/python2.7/dist-packages/samba/dcerpc/dnsserver.so
# by generator 1.143
""" dnsserver DCE/RPC """

# imports
import dcerpc as __dcerpc
import misc as __misc
import talloc as __talloc


# Variables with simple values

DNSSRV_TYPEID_ADDRARRAY = 34
DNSSRV_TYPEID_AUTOCONFIGURE = 42
DNSSRV_TYPEID_BUFFER = 5

DNSSRV_TYPEID_DP_ENUM = 28
DNSSRV_TYPEID_DP_INFO = 29
DNSSRV_TYPEID_DP_LIST = 30

DNSSRV_TYPEID_DWORD = 1

DNSSRV_TYPEID_ENLIST_DP = 31

DNSSRV_TYPEID_ENUM_ZONES_FILTER = 33

DNSSRV_TYPEID_FORWARDERS = 37

DNSSRV_TYPEID_FORWARDERS_DOTNET = 20
DNSSRV_TYPEID_FORWARDERS_W2K = 8

DNSSRV_TYPEID_IPARRAY = 4

DNSSRV_TYPEID_IP_VALIDATE = 41

DNSSRV_TYPEID_LPSTR = 2
DNSSRV_TYPEID_LPWSTR = 3

DNSSRV_TYPEID_NAME_AND_PARAM = 15

DNSSRV_TYPEID_NULL = 0

DNSSRV_TYPEID_SERVER_INFO = 35

DNSSRV_TYPEID_SERVER_INFO_DOTNET = 19
DNSSRV_TYPEID_SERVER_INFO_W2K = 6

DNSSRV_TYPEID_STATS = 7

DNSSRV_TYPEID_UNICODE_STRING_LIST = 44

DNSSRV_TYPEID_UTF8_STRING_LIST = 43

DNSSRV_TYPEID_ZONE = 21

DNSSRV_TYPEID_ZONE_CHANGE_DP = 32

DNSSRV_TYPEID_ZONE_CREATE = 40

DNSSRV_TYPEID_ZONE_CREATE_DOTNET = 26
DNSSRV_TYPEID_ZONE_CREATE_W2K = 14

DNSSRV_TYPEID_ZONE_DATABASE = 24

DNSSRV_TYPEID_ZONE_DATABASE_W2K = 12

DNSSRV_TYPEID_ZONE_EXPORT = 18
DNSSRV_TYPEID_ZONE_INFO = 36

DNSSRV_TYPEID_ZONE_INFO_DOTNET = 22
DNSSRV_TYPEID_ZONE_INFO_W2K = 10

DNSSRV_TYPEID_ZONE_LIST = 27

DNSSRV_TYPEID_ZONE_LIST_W2K = 16

DNSSRV_TYPEID_ZONE_RENAME = 17
DNSSRV_TYPEID_ZONE_SECONDARIES = 38

DNSSRV_TYPEID_ZONE_SECONDARIES_DOTNET = 23
DNSSRV_TYPEID_ZONE_SECONDARIES_W2K = 11

DNSSRV_TYPEID_ZONE_TYPE_RESET = 39

DNSSRV_TYPEID_ZONE_TYPE_RESET_DOTNET = 25
DNSSRV_TYPEID_ZONE_TYPE_RESET_W2K = 13

DNSSRV_TYPEID_ZONE_W2K = 9

DNS_ALLOW_ALL_NAMES = 3

DNS_ALLOW_MULTIBYTE_NAMES = 2

DNS_ALLOW_NONRFC_NAMES = 1

DNS_ALLOW_RFC_NAMES_ONLY = 0

DNS_BOOT_METHOD_DIRECTORY = 3
DNS_BOOT_METHOD_FILE = 1
DNS_BOOT_METHOD_REGISTRY = 2
DNS_BOOT_METHOD_UNINITIALIZED = 0

DNS_CLIENT_VERSION_DOTNET = 393216
DNS_CLIENT_VERSION_LONGHORN = 458752
DNS_CLIENT_VERSION_W2K = 0

DNS_DP_AUTOCREATED = 1
DNS_DP_DELETED = 32

DNS_DP_DOMAIN_DEFAULT = 4

DNS_DP_ENLISTED = 16

DNS_DP_FOREST_DEFAULT = 8

DNS_DP_LEGACY = 2
DNS_DP_OKAY = 0

DNS_DP_STATE_REPL_INCOMING = 1
DNS_DP_STATE_REPL_OUTGOING = 2

DNS_DP_STATE_UNKNOWN = 3

DNS_EVENT_LOG_ERROR_TYPE = 1

DNS_EVENT_LOG_INFORMATION_TYPE = 4

DNS_EVENT_LOG_SUCCESS = 0

DNS_EVENT_LOG_WARNING_TYPE = 2

DNS_IPVAL_DNS_DELEGATIONS = 4
DNS_IPVAL_DNS_FORWARDERS = 2
DNS_IPVAL_DNS_ROOTHINTS = 1
DNS_IPVAL_DNS_SERVERS = 0

DNS_IPVAL_DNS_ZONE_MASTERS = 3

DNS_IPVAL_INVALID_ADDR = 1

DNS_IPVAL_NOT_AUTH_FOR_ZONE = 4

DNS_IPVAL_NO_RESPONSE = 3
DNS_IPVAL_NO_TCP = 2147483648

DNS_IPVAL_UNKNOWN_ERROR = 255

DNS_IPVAL_UNREACHABLE = 2

DNS_RPC_AUTOCONFIG_ALL = 4294967295

DNS_RPC_AUTOCONFIG_INTERNAL_FORWARDERS = 2

DNS_RPC_AUTOCONFIG_INTERNAL_RETURN_ERROR = 32768

DNS_RPC_AUTOCONFIG_INTERNAL_ROOTHINTS = 1
DNS_RPC_AUTOCONFIG_INTERNAL_SELFPOINT = 16

DNS_RPC_AUTOCONFIG_INTERNAL_SELFPOINT_APPEND = 64
DNS_RPC_AUTOCONFIG_INTERNAL_SELFPOINT_PREPEND = 32

DNS_RPC_AUTOCONFIG_INTERNAL_ZONES = 4

DNS_RPC_USE_ALL_PROTOCOLS = 4294967295

DNS_RPC_USE_LPC = 4

DNS_RPC_USE_NAMED_PIPE = 2

DNS_RPC_USE_TCPIP = 1

DNS_RPC_VIEW_ADDITIONAL_DATA = 16

DNS_RPC_VIEW_AUTHORITY_DATA = 1

DNS_RPC_VIEW_CACHE_DATA = 2

DNS_RPC_VIEW_GLUE_DATA = 4

DNS_RPC_VIEW_NO_CHILDREN = 65536

DNS_RPC_VIEW_ONLY_CHILDREN = 131072

DNS_RPC_VIEW_ROOT_HINT_DATA = 8

DNS_RPC_ZONE_AGING = 32
DNS_RPC_ZONE_AUTOCREATED = 8
DNS_RPC_ZONE_DSINTEGRATED = 16
DNS_RPC_ZONE_PAUSED = 1
DNS_RPC_ZONE_READONLY = 256
DNS_RPC_ZONE_REVERSE = 4
DNS_RPC_ZONE_SHUTDOWN = 2

DNS_RPC_ZONE_UPDATE_SECURE = 128
DNS_RPC_ZONE_UPDATE_UNSECURE = 64

DNS_ZONE_NOTIFY_ALL_SECONDARIES = 1

DNS_ZONE_NOTIFY_LIST_ONLY = 2

DNS_ZONE_NOTIFY_OFF = 0

DNS_ZONE_REQUEST_AUTO = 8
DNS_ZONE_REQUEST_CACHE = 4

DNS_ZONE_REQUEST_CUSTOM_DP = 4096

DNS_ZONE_REQUEST_DOMAIN_DP = 1024

DNS_ZONE_REQUEST_DS = 256

DNS_ZONE_REQUEST_FOREST_DP = 2048

DNS_ZONE_REQUEST_FORWARD = 16
DNS_ZONE_REQUEST_FORWARDER = 64

DNS_ZONE_REQUEST_LEGACY_DP = 8192

DNS_ZONE_REQUEST_NON_DS = 512

DNS_ZONE_REQUEST_PRIMARY = 1
DNS_ZONE_REQUEST_REVERSE = 32
DNS_ZONE_REQUEST_SECONDARY = 2
DNS_ZONE_REQUEST_STUB = 128

DNS_ZONE_SECSECURE_LIST_ONLY = 2

DNS_ZONE_SECSECURE_NO_SECURITY = 0
DNS_ZONE_SECSECURE_NO_XFER = 3

DNS_ZONE_SECSECURE_NS_ONLY = 1

ERROR_SUCCESS = 0

# no functions
# classes

from abstract_syntax import abstract_syntax
from dnsserver import dnsserver
from DNSSRV_STAT import DNSSRV_STAT
from DNSSRV_STAT_HEADER import DNSSRV_STAT_HEADER
from DNS_ADDR import DNS_ADDR
from DNS_ADDR_ARRAY import DNS_ADDR_ARRAY
from DNS_EXTENSION import DNS_EXTENSION
from DNS_RPC_AUTOCONFIGURE import DNS_RPC_AUTOCONFIGURE
from DNS_RPC_BUFFER import DNS_RPC_BUFFER
from DNS_RPC_DP_ENUM import DNS_RPC_DP_ENUM
from DNS_RPC_DP_INFO import DNS_RPC_DP_INFO
from DNS_RPC_DP_LIST import DNS_RPC_DP_LIST
from DNS_RPC_DP_REPLICA import DNS_RPC_DP_REPLICA
from DNS_RPC_ENLIST_DP import DNS_RPC_ENLIST_DP
from DNS_RPC_ENUM_ZONES_FILTER import DNS_RPC_ENUM_ZONES_FILTER
from DNS_RPC_FORWARDERS_DOTNET import DNS_RPC_FORWARDERS_DOTNET
from DNS_RPC_FORWARDERS_LONGHORN import DNS_RPC_FORWARDERS_LONGHORN
from DNS_RPC_FORWARDERS_W2K import DNS_RPC_FORWARDERS_W2K
from DNS_RPC_IP_VALIDATE import DNS_RPC_IP_VALIDATE
from DNS_RPC_NAME import DNS_RPC_NAME
from DNS_RPC_NAME_AND_PARAM import DNS_RPC_NAME_AND_PARAM
from DNS_RPC_NODE import DNS_RPC_NODE
from DNS_RPC_RECORD import DNS_RPC_RECORD
from DNS_RPC_RECORDS import DNS_RPC_RECORDS
from DNS_RPC_RECORDS_ARRAY import DNS_RPC_RECORDS_ARRAY
from DNS_RPC_RECORD_BUF import DNS_RPC_RECORD_BUF
from DNS_RPC_RECORD_NAME_PREFERENCE import DNS_RPC_RECORD_NAME_PREFERENCE
from DNS_RPC_RECORD_SOA import DNS_RPC_RECORD_SOA
from DNS_RPC_RECORD_SRV import DNS_RPC_RECORD_SRV
from DNS_RPC_RECORD_STRING import DNS_RPC_RECORD_STRING
from DNS_RPC_SERVER_INFO_DOTNET import DNS_RPC_SERVER_INFO_DOTNET
from DNS_RPC_SERVER_INFO_LONGHORN import DNS_RPC_SERVER_INFO_LONGHORN
from DNS_RPC_SERVER_INFO_W2K import DNS_RPC_SERVER_INFO_W2K
from DNS_RPC_UTF8_STRING_LIST import DNS_RPC_UTF8_STRING_LIST
from DNS_RPC_ZONE_CHANGE_DP import DNS_RPC_ZONE_CHANGE_DP
from DNS_RPC_ZONE_CREATE_INFO_DOTNET import DNS_RPC_ZONE_CREATE_INFO_DOTNET
from DNS_RPC_ZONE_CREATE_INFO_LONGHORN import DNS_RPC_ZONE_CREATE_INFO_LONGHORN
from DNS_RPC_ZONE_CREATE_INFO_W2K import DNS_RPC_ZONE_CREATE_INFO_W2K
from DNS_RPC_ZONE_DATABASE_DOTNET import DNS_RPC_ZONE_DATABASE_DOTNET
from DNS_RPC_ZONE_DATABASE_W2K import DNS_RPC_ZONE_DATABASE_W2K
from DNS_RPC_ZONE_DOTNET import DNS_RPC_ZONE_DOTNET
from DNS_RPC_ZONE_EXPORT_INFO import DNS_RPC_ZONE_EXPORT_INFO
from DNS_RPC_ZONE_INFO_DOTNET import DNS_RPC_ZONE_INFO_DOTNET
from DNS_RPC_ZONE_INFO_LONGHORN import DNS_RPC_ZONE_INFO_LONGHORN
from DNS_RPC_ZONE_INFO_W2K import DNS_RPC_ZONE_INFO_W2K
from DNS_RPC_ZONE_LIST_DOTNET import DNS_RPC_ZONE_LIST_DOTNET
from DNS_RPC_ZONE_LIST_W2K import DNS_RPC_ZONE_LIST_W2K
from DNS_RPC_ZONE_SECONDARIES_DOTNET import DNS_RPC_ZONE_SECONDARIES_DOTNET
from DNS_RPC_ZONE_SECONDARIES_LONGHORN import DNS_RPC_ZONE_SECONDARIES_LONGHORN
from DNS_RPC_ZONE_SECONDARIES_W2K import DNS_RPC_ZONE_SECONDARIES_W2K
from DNS_RPC_ZONE_W2K import DNS_RPC_ZONE_W2K
from IP4_ARRAY import IP4_ARRAY
